version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin # Default admin user (change in production)
      MINIO_ROOT_PASSWORD: minioadmin123 # Change this in production!
    ports:
      - '9000:9000' # API port (S3 access)
      - '9001:9001' # Web UI (Console)
    volumes:
      - minio_data:/data # Persists data between restarts
    restart: unless-stopped

volumes:
  minio_data: # Named volume for MinIO storage
