version: '3.8'

services:
  minio:
    image: minio/minio
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin # Default admin user (change in production)
      MINIO_ROOT_PASSWORD: minioadmin123 # Change this in production!
    ports:
      - '9000:9000' # API port (S3 access)
      - '9001:9001' # Web UI (Console)
    volumes:
      - minio_data:/data # Persists data between restarts
    restart: unless-stopped
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - '5672:5672' # AMQP port
      - '15672:15672' # Management UI port
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    restart: unless-stopped

  db:
    container_name: db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: dbname # The PostgreSQL default database (automatically created at first launch)
    ports:
      - 8006:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d

volumes:
  minio_data: # Named volume for MinIO storage
  rabbitmq_data:
  postgres_data:
